 GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFubmFoIiwiaWF0IjoxNjA3MTc0NDk4fQ.sfbCZmQKan9SxuTP7evp2GKfrxyHU8DpMa6lEhSapk4

###

POST http://localhost:3000/login
Content-Type: application/json

{
	"username": "Hannah"
}